import type { Listing } from './types';

// Cloudinary cloud: dkn6tnxao, folder: homesconnect (Stephen uploads via console).
// Until images are uploaded these resolve to placeholder transformation URLs;
// once the named images exist in Cloudinary the same paths serve real photos.
const CLD = 'https://res.cloudinary.com/dkn6tnxao/image/upload';
const T = (name: string) => `${CLD}/c_fill/w_900/h_600/q_auto/f_auto/homesconnect/${name}.jpg`;

// 6 hero property images — keyed by descriptive slug.
const IMG = {
  karoo: T('property-01-karoo-farmhouse'),
  bushveldLodge: T('property-02-bushveld-lodge'),
  oceanModern: T('property-03-kzn-ocean-modern'),
  sandtonMansion: T('property-04-sandton-mansion'),
  capeDutch: T('property-05-cape-dutch'),
  cptMountain: T('property-06-cpt-mountain'),
};

function entry(
  p: Omit<Listing, 'status' | 'sellerType' | 'whatsapp' | 'sizeSqm' | 'address'> &
    Partial<Pick<Listing, 'status' | 'sellerType' | 'whatsapp' | 'sizeSqm' | 'address'>>
): Listing {
  return { status: 'active', sellerType: 'agent', whatsapp: '', sizeSqm: 0, address: '', ...p };
}

export const SEED_LISTINGS: Listing[] = [
  // ===== Gauteng (8) =====
  entry({
    id: 'HC001', type: 'sale', tier: 'enhanced',
    title: 'Architect-Designed Sandton Mansion',
    price: 4850000, priceDisplay: 'R 4,850,000',
    bedrooms: 4, bathrooms: 4, garage: 3, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Sandton', city: 'Johannesburg', province: 'Gauteng',
    description: 'Striking double-storey residence with floor-to-ceiling glass, designer pool and landscaped grounds. Walking distance to Sandton CBD.',
    imageUrl: IMG.sandtonMansion, image2: IMG.cptMountain, image3: IMG.bushveldLodge,
    agentName: 'Sarah Mokoena', agentPhone: '0821234567', agentAgency: 'Mokoena Properties',
    featured: true, dateListed: '2026-05-12',
  }),
  entry({
    id: 'HC002', type: 'sale', tier: 'basic',
    title: 'Family Home in Faerie Glen',
    price: 2100000, priceDisplay: 'R 2,100,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Faerie Glen', city: 'Pretoria', province: 'Gauteng',
    description: 'Sun-filled face-brick home in a quiet cul-de-sac. Open-plan living, large garden, close to top schools.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Pieter van der Merwe', agentPhone: '0834567890', agentAgency: 'PVDM Realty',
    featured: false, dateListed: '2026-05-10',
  }),
  entry({
    id: 'HC003', type: 'rent', tier: 'basic',
    title: 'Modern 3-Bed in Garsfontein',
    price: 13500, priceDisplay: 'R 13,500/mo',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Garsfontein', city: 'Pretoria', province: 'Gauteng',
    description: 'Neat lock-up-and-go family home in a secure boomed area. Available 1 June.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Lerato Dube', agentPhone: '0845678901', agentAgency: 'Capital Letting',
    featured: false, dateListed: '2026-05-08',
  }),
  entry({
    id: 'HC004', type: 'sale', tier: 'basic',
    title: 'Midrand Townhouse — Move-In Ready',
    price: 1450000, priceDisplay: 'R 1,450,000',
    bedrooms: 2, bathrooms: 2, garage: 1, garden: false, pool: false, petFriendly: false,
    propertyType: 'townhouse', suburb: 'Carlswald', city: 'Midrand', province: 'Gauteng',
    description: 'Bright modern townhouse in a secure complex with pool and clubhouse.',
    imageUrl: IMG.sandtonMansion, image2: '', image3: '',
    agentName: 'Thabo Sithole', agentPhone: '0826543210', agentAgency: 'Sithole Properties',
    featured: false, dateListed: '2026-05-09',
  }),
  entry({
    id: 'HC005', type: 'sale', tier: 'enhanced',
    title: 'Family Home in Centurion',
    price: 1800000, priceDisplay: 'R 1,800,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Eldoraigne', city: 'Centurion', province: 'Gauteng',
    description: 'Established family home with separate flatlet, ideal for extended family or rental income.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Pieter van der Merwe', agentPhone: '0834567890', agentAgency: 'PVDM Realty',
    featured: false, dateListed: '2026-05-07',
  }),
  entry({
    id: 'HC006', type: 'sale', tier: 'agency',
    title: 'Bryanston Executive Residence',
    price: 3500000, priceDisplay: 'R 3,500,000',
    bedrooms: 4, bathrooms: 3, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Bryanston', city: 'Sandton', province: 'Gauteng',
    description: 'Generous family living with entertainment patio overlooking pool and koi pond.',
    imageUrl: IMG.sandtonMansion, image2: IMG.cptMountain, image3: '',
    agentName: 'Sarah Mokoena', agentPhone: '0821234567', agentAgency: 'Mokoena Properties',
    featured: true, dateListed: '2026-05-11',
  }),
  entry({
    id: 'HC007', type: 'rent', tier: 'basic',
    title: 'Fourways Apartment with Views',
    price: 12000, priceDisplay: 'R 12,000/mo',
    bedrooms: 2, bathrooms: 2, garage: 1, garden: false, pool: true, petFriendly: false,
    propertyType: 'apartment', suburb: 'Fourways', city: 'Sandton', province: 'Gauteng',
    description: 'Sleek apartment in a security complex with gym, pool and concierge.',
    imageUrl: IMG.sandtonMansion, image2: '', image3: '',
    agentName: 'Lerato Dube', agentPhone: '0845678901', agentAgency: 'Capital Letting',
    featured: false, dateListed: '2026-05-06',
  }),
  entry({
    id: 'HC008', type: 'sale', tier: 'basic',
    title: 'Randburg Townhouse — Pet Friendly',
    price: 1650000, priceDisplay: 'R 1,650,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'townhouse', suburb: 'Ferndale', city: 'Randburg', province: 'Gauteng',
    description: 'Spacious end-unit with private garden, ideal for a young family.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Thabo Sithole', agentPhone: '0826543210', agentAgency: 'Sithole Properties',
    featured: false, dateListed: '2026-05-05',
  }),

  // ===== Western Cape (6) =====
  entry({
    id: 'HC009', type: 'rent', tier: 'enhanced',
    title: 'Sea Point Apartment with Ocean Views',
    price: 22500, priceDisplay: 'R 22,500/mo',
    bedrooms: 2, bathrooms: 2, garage: 1, garden: false, pool: true, petFriendly: false,
    propertyType: 'apartment', suburb: 'Sea Point', city: 'Cape Town', province: 'Western Cape',
    description: 'Renovated apartment on the Promenade, panoramic Atlantic views, walk to cafés.',
    imageUrl: IMG.cptMountain, image2: IMG.oceanModern, image3: '',
    agentName: 'Marius Joubert', agentPhone: '0823344556', agentAgency: 'Atlantic Letting',
    featured: false, dateListed: '2026-05-10',
  }),
  entry({
    id: 'HC010', type: 'sale', tier: 'enhanced',
    title: 'Cape Dutch Estate in Stellenbosch',
    price: 3200000, priceDisplay: 'R 3,200,000',
    bedrooms: 3, bathrooms: 3, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Mostertsdrift', city: 'Stellenbosch', province: 'Western Cape',
    description: 'Heritage Cape Dutch home with rose garden, mountain views and original yellowwood floors.',
    imageUrl: IMG.capeDutch, image2: IMG.cptMountain, image3: '',
    agentName: 'Elsabe Smit', agentPhone: '0824455667', agentAgency: 'Cape Heritage Realty',
    featured: true, dateListed: '2026-05-13',
  }),
  entry({
    id: 'HC011', type: 'sale', tier: 'basic',
    title: 'Paarl Winelands Family Home',
    price: 2800000, priceDisplay: 'R 2,800,000',
    bedrooms: 4, bathrooms: 3, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Val de Vie', city: 'Paarl', province: 'Western Cape',
    description: 'Modern family home in a secure estate with golf course, vineyards and equestrian centre.',
    imageUrl: IMG.capeDutch, image2: '', image3: '',
    agentName: 'Elsabe Smit', agentPhone: '0824455667', agentAgency: 'Cape Heritage Realty',
    featured: false, dateListed: '2026-05-09',
  }),
  entry({
    id: 'HC012', type: 'sale', tier: 'basic',
    title: 'Durbanville Townhouse',
    price: 2100000, priceDisplay: 'R 2,100,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'townhouse', suburb: 'Sonstraal', city: 'Durbanville', province: 'Western Cape',
    description: 'Light, modern townhouse close to top schools and the wine route.',
    imageUrl: IMG.capeDutch, image2: '', image3: '',
    agentName: 'Marius Joubert', agentPhone: '0823344556', agentAgency: 'Atlantic Letting',
    featured: false, dateListed: '2026-05-08',
  }),
  entry({
    id: 'HC013', type: 'sale', tier: 'basic',
    title: 'Bloubergstrand Beach Apartment',
    price: 1950000, priceDisplay: 'R 1,950,000',
    bedrooms: 2, bathrooms: 2, garage: 1, garden: false, pool: true, petFriendly: false,
    propertyType: 'apartment', suburb: 'Bloubergstrand', city: 'Cape Town', province: 'Western Cape',
    description: 'Sunny apartment a short walk to the beach with Table Mountain views.',
    imageUrl: IMG.oceanModern, image2: IMG.cptMountain, image3: '',
    agentName: 'Marius Joubert', agentPhone: '0823344556', agentAgency: 'Atlantic Letting',
    featured: false, dateListed: '2026-05-07',
  }),
  entry({
    id: 'HC014', type: 'rent', tier: 'agency',
    title: 'Camps Bay Luxury Apartment',
    price: 35000, priceDisplay: 'R 35,000/mo',
    bedrooms: 3, bathrooms: 3, garage: 2, garden: false, pool: true, petFriendly: false,
    propertyType: 'apartment', suburb: 'Camps Bay', city: 'Cape Town', province: 'Western Cape',
    description: 'Designer apartment with sea views, infinity pool and 24/7 concierge.',
    imageUrl: IMG.cptMountain, image2: IMG.oceanModern, image3: '',
    agentName: 'Marius Joubert', agentPhone: '0823344556', agentAgency: 'Atlantic Letting',
    featured: true, dateListed: '2026-05-12',
  }),

  // ===== KwaZulu-Natal (5) =====
  entry({
    id: 'HC015', type: 'sale', tier: 'enhanced',
    title: 'Glenashley Family Home',
    price: 2250000, priceDisplay: 'R 2,250,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Glenashley', city: 'Durban', province: 'KwaZulu-Natal',
    description: 'Subtropical garden home a short drive from the beachfront and uMhlanga Village.',
    imageUrl: IMG.oceanModern, image2: '', image3: '',
    agentName: 'Naidoo Pillay', agentPhone: '0827788990', agentAgency: 'Coastal Homes',
    featured: false, dateListed: '2026-05-11',
  }),
  entry({
    id: 'HC016', type: 'sale', tier: 'enhanced',
    title: 'Umhlanga Beachside Apartment',
    price: 2400000, priceDisplay: 'R 2,400,000',
    bedrooms: 2, bathrooms: 2, garage: 1, garden: false, pool: true, petFriendly: false,
    propertyType: 'apartment', suburb: 'Umhlanga Rocks', city: 'Umhlanga', province: 'KwaZulu-Natal',
    description: 'Modern apartment with direct beach access and panoramic Indian Ocean views.',
    imageUrl: IMG.oceanModern, image2: '', image3: '',
    agentName: 'Naidoo Pillay', agentPhone: '0827788990', agentAgency: 'Coastal Homes',
    featured: true, dateListed: '2026-05-13',
  }),
  entry({
    id: 'HC017', type: 'sale', tier: 'agency',
    title: 'Ballito Beachfront Family Home',
    price: 3100000, priceDisplay: 'R 3,100,000',
    bedrooms: 4, bathrooms: 3, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Ballito', city: 'Ballito', province: 'KwaZulu-Natal',
    description: 'Spacious home in Simbithi Eco-Estate, minutes from the sea.',
    imageUrl: IMG.oceanModern, image2: IMG.sandtonMansion, image3: '',
    agentName: 'Naidoo Pillay', agentPhone: '0827788990', agentAgency: 'Coastal Homes',
    featured: false, dateListed: '2026-05-09',
  }),
  entry({
    id: 'HC018', type: 'sale', tier: 'basic',
    title: 'Hillcrest Family Home',
    price: 1850000, priceDisplay: 'R 1,850,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Hillcrest', city: 'Durban', province: 'KwaZulu-Natal',
    description: 'Established family home in a leafy suburb close to top private schools.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Naidoo Pillay', agentPhone: '0827788990', agentAgency: 'Coastal Homes',
    featured: false, dateListed: '2026-05-08',
  }),
  entry({
    id: 'HC019', type: 'rent', tier: 'basic',
    title: 'La Lucia Family Rental',
    price: 18500, priceDisplay: 'R 18,500/mo',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'La Lucia', city: 'Umhlanga', province: 'KwaZulu-Natal',
    description: 'Family home in a quiet street, walking distance to the beach.',
    imageUrl: IMG.oceanModern, image2: '', image3: '',
    agentName: 'Naidoo Pillay', agentPhone: '0827788990', agentAgency: 'Coastal Homes',
    featured: false, dateListed: '2026-05-06',
  }),

  // ===== Limpopo (3) =====
  entry({
    id: 'HC020', type: 'sale', tier: 'enhanced',
    title: 'Vaalwater Bushveld Retreat',
    price: 2800000, priceDisplay: 'R 2,800,000',
    bedrooms: 4, bathrooms: 3, garage: 2, garden: true, pool: true, petFriendly: true,
    propertyType: 'house', suburb: 'Vaalwater', city: 'Vaalwater', province: 'Limpopo',
    description: 'Thatched bushveld home on a private game estate with infinity pool and sundowner deck.',
    imageUrl: IMG.bushveldLodge, image2: IMG.karoo, image3: '',
    agentName: 'Adriaan Botha', agentPhone: '0829988776', agentAgency: 'Waterberg Realty',
    featured: true, dateListed: '2026-05-12',
  }),
  entry({
    id: 'HC021', type: 'sale', tier: 'basic',
    title: 'Lephalale Family Home',
    price: 1200000, priceDisplay: 'R 1,200,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Onverwacht', city: 'Lephalale', province: 'Limpopo',
    description: 'Comfortable family home close to schools and Medupi power station.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Adriaan Botha', agentPhone: '0829988776', agentAgency: 'Waterberg Realty',
    featured: false, dateListed: '2026-05-07',
  }),
  entry({
    id: 'HC022', type: 'sale', tier: 'basic',
    title: 'Modimolle Starter Home',
    price: 950000, priceDisplay: 'R 950,000',
    bedrooms: 3, bathrooms: 2, garage: 1, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Nylstroom', city: 'Modimolle', province: 'Limpopo',
    description: 'Charming starter home with established garden in town.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Adriaan Botha', agentPhone: '0829988776', agentAgency: 'Waterberg Realty',
    featured: false, dateListed: '2026-05-05',
  }),

  // ===== Other (3) =====
  entry({
    id: 'HC023', type: 'sale', tier: 'basic',
    title: 'Port Elizabeth Family Home',
    price: 1600000, priceDisplay: 'R 1,600,000',
    bedrooms: 3, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Walmer', city: 'Port Elizabeth', province: 'Eastern Cape',
    description: 'Well-loved home minutes from the beachfront and top schools.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Yolanda Naude', agentPhone: '0823344667', agentAgency: 'Bay Realty',
    featured: false, dateListed: '2026-05-08',
  }),
  entry({
    id: 'HC024', type: 'sale', tier: 'basic',
    title: 'Bloemfontein Family Home',
    price: 1350000, priceDisplay: 'R 1,350,000',
    bedrooms: 4, bathrooms: 2, garage: 2, garden: true, pool: false, petFriendly: true,
    propertyType: 'house', suburb: 'Langenhoven Park', city: 'Bloemfontein', province: 'Free State',
    description: 'Spacious face-brick home in a quiet, established neighbourhood.',
    imageUrl: IMG.karoo, image2: '', image3: '',
    agentName: 'Johan Pretorius', agentPhone: '0825566778', agentAgency: 'Free State Homes',
    featured: false, dateListed: '2026-05-06',
  }),
  entry({
    id: 'HC025', type: 'rent', tier: 'basic',
    title: 'Potchefstroom Student Apartment',
    price: 8500, priceDisplay: 'R 8,500/mo',
    bedrooms: 2, bathrooms: 1, garage: 1, garden: false, pool: false, petFriendly: false,
    propertyType: 'apartment', suburb: 'Bult', city: 'Potchefstroom', province: 'North West',
    description: 'Secure apartment close to NWU campus, ideal for students or young professionals.',
    imageUrl: IMG.sandtonMansion, image2: '', image3: '',
    agentName: 'Johan Pretorius', agentPhone: '0825566778', agentAgency: 'Free State Homes',
    featured: false, dateListed: '2026-05-04',
  }),
];
